MASK_PATH = 'data\\Test_005_Mask.tif'
WSI_PATH = 'data\\Test_005.tif'
CHECKPOINT_PATH = 'data\\model.ckpt-35'

LEVEL_UPGRADE = 5
LEVEL_FETCH = 1
PATCH_SIZE = 252 #124
OUTPUT_SIZE = 164 #36
DIFF_SIZE = PATCH_SIZE - OUTPUT_SIZE
BATCH_SIZE = 64